(define (largersum x y z)
		(if (and (> x y)
				 (> x z))
			(if (> y z)
				(+ x y)
				(+ x z))
			(if (> x y)
				(+ x z)
				(if (> x z)
					(+ x y)
					(+ y z)))))

;;shorter implemention
(define (largersum x y z)
		(if (and (< x y)
				 (< x z))
			(+ y z)
			(if (< y z)
				(+ x z)
				(+ x y))))